export const leagues = [
  { id: "140", name: "La Liga" },
  { id: "39", name: "Premier League" },
  { id: "61", name: "Ligue 1" },
  { id: "2", name: "UEFA Champions League" },
  { id: "3", name: "UEFA Europa League" },
  { id: "253", name: "MLS" },
  { id: "135", name: "Série A" },
  { id: "78", name: "Bundesliga" },
  { id: "1", name: "Wolrd Cup" },
  { id: "4", name: "Euro Championship" },
  { id: "960", name: "Euro Championship - Qualification" },
  { id: "9", name: "Copa America" },
  { id: "34", name: "World Cup - Qualification South America" },
  { id: "6", name: "Africa Cup of Nations" },
  { id: "531", name: "UEFA Super Cup" },
  { id: "45", name: "FA Cup" },
  { id: "556", name: "Spain Super Cup" },
  { id: "143", name: "Copa del Rey" },
  { id: "667", name: "Friendlies Clubs" },
];
